springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /v3/api-docs

logging:
  org:
    springframework:
      web:
        client:
          RestTemplate: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb+srv://<username>:<pwd>@<cluster>.mongodb.net/test-clean
      database: test-clean
api.environment: develop