springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /v3/api-docs

logging:
  org:
    springframework:
      web:
        client:
          RestTemplate: DEBUG